[serve.static]
plugins = ["bun-plugin-tailwind"]
env = "BUN_PUBLIC_*"

[test]
preload = ["./src/setupTests.ts"]

[install]
linker = "isolated"
auto = "force"

[run]
# Always use `bun` instead of `node`, even if scripts call `node`.
bun = true
